import PageHeader from "../components/PageHeader"

function Inversiones() {
    return (
        <>
            <PageHeader titulo="Inversiones" />
            <section className="padded">
                <div className="container">
                    <h2>Bienvenido</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi modi omnis vitae distinctio maiores ullam blanditiis sunt similique, dolorem totam maxime quasi iste odit, perferendis cupiditate beatae incidunt nihil aut deleniti consequuntur, voluptas architecto! Repellendus maxime, nisi quibusdam dignissimos commodi dolore quae enim corrupti atque voluptate ex, autem fuga ipsum, placeat veniam rerum magni animi repellat. Voluptatibus unde incidunt debitis, possimus excepturi enim voluptas, optio dolor quae inventore fugit, nihil quas? Sunt quis veniam ipsam, perferendis vel impedit modi odio dignissimos voluptates. Et eius optio ad amet iusto earum consequatur dolore. Ullam tempora hic sit animi. Nemo possimus odit in!</p>
                    <p>Iusto veritatis dignissimos sequi adipisci quos consequatur praesentium perspiciatis tempore perferendis maiores accusamus quae hic possimus accusantium sapiente labore vitae atque nostrum, soluta dicta amet. Maiores, fuga modi alias facilis tenetur tempore velit corrupti ex iusto assumenda ullam provident? Autem temporibus harum eaque impedit error, similique dolor distinctio ratione eveniet, consectetur quibusdam enim! Assumenda doloremque ipsam inventore odio ut accusamus, necessitatibus, maxime et voluptatem exercitationem facere rem illo nam nihil minima, natus numquam? Doloribus autem culpa velit esse nulla ab adipisci facilis eum maiores? Maxime soluta possimus mollitia aperiam similique vel vero, esse, delectus eum dolores eligendi officia in animi?</p>
                    <p>A deleniti repellat atque commodi? Molestiae, possimus perspiciatis rerum nam corrupti ratione molestias saepe veritatis fugit explicabo dignissimos rem provident, sit animi vitae? Hic soluta est, accusamus expedita dolorem libero laboriosam veniam obcaecati maiores molestiae distinctio odit voluptatem reiciendis animi, nobis eaque? Magnam, voluptatibus aliquid. Eos sequi accusantium corrupti rerum assumenda ex quod ad similique numquam, sit doloribus magni sint beatae cumque quibusdam, aperiam quam! Omnis exercitationem optio labore dicta placeat, vero, at recusandae vel eos sed ut doloremque vitae nostrum praesentium cumque distinctio quidem illo iure, provident quo. Nemo iste quis distinctio eligendi. Autem exercitationem minus repudiandae sit adipisci.</p>
                    <p>Vero, doloribus, dolor accusantium, reiciendis quibusdam cum architecto nemo consequatur corporis illo voluptas quia corrupti veniam enim officia impedit tenetur facere ad fugiat quaerat minus! Praesentium, quod aliquam. Possimus officiis harum eos numquam distinctio quam repellendus ad expedita magni, ut, dolore necessitatibus. Vitae culpa consequatur consectetur facere officiis aut itaque quibusdam odio totam, cum delectus, fugit, veniam cumque commodi velit aliquid dicta? Numquam architecto repellendus veniam sequi dolorum sint quidem similique veritatis itaque, aut ex enim nesciunt non facilis tempore accusantium recusandae earum voluptatibus perspiciatis nisi laborum corrupti! Ex excepturi aliquid culpa. Illo, sapiente temporibus. Voluptate vero vel harum perspiciatis!</p>
                    <p>Neque itaque non molestias perspiciatis tenetur excepturi iusto quibusdam distinctio odio, commodi, provident quidem veritatis cum tempore incidunt fuga ut enim? Maxime officiis reprehenderit magni nam nostrum molestias velit, ut cum ullam totam nemo quaerat alias nulla dolorem! Nisi neque vel nemo? Vitae, in explicabo, consectetur veniam debitis ab non eaque incidunt dolores molestiae fuga, ipsum ea autem beatae ducimus dicta illo quae asperiores dolor. Quod, magni eos eaque vel eum incidunt labore sint beatae sit laborum, deleniti repellat. Veniam at unde expedita dicta quo dignissimos voluptatum? Beatae, corrupti, repudiandae placeat ipsam dolores aliquam voluptate expedita alias enim in vitae.</p>
                    <p>Odio libero eum cupiditate eos? At facere quaerat, porro doloremque harum et deserunt ea similique consequuntur atque sint esse exercitationem repellendus? Asperiores, nam saepe? Vitae repellat officia, error deleniti rerum dolorum repellendus, inventore dolor similique illum quae in molestias amet sint, neque facilis distinctio possimus animi repudiandae laudantium commodi eius odio fuga. Nostrum voluptatibus atque adipisci rem recusandae ea voluptate sit ab, eligendi vel provident saepe culpa quod reiciendis sequi minima quos architecto ipsa harum commodi assumenda! Ea nam aliquid facilis asperiores quos, sequi natus dolor nemo nostrum odio atque eos, repellat non ipsam mollitia id quod, voluptas nisi dicta!</p>
                </div>
            </section>
        </>
    )
}

export default Inversiones